/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-27 03:46:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script   src=\"https://code.jquery.com/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("	loadData(\"\",\"\");\r\n");
      out.write("	$(\"#send\").click(function(){\r\n");
      out.write("		var postString = {\r\n");
      out.write("				\"name\" : $(\"#name\").val(),\r\n");
      out.write("				\"content\" : $(\"#content\").val(),\r\n");
      out.write("			    \"grade\" : $(\"input:radio[name='grade']:checked\").val()\r\n");
      out.write("		}\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			url : \"insert\",\r\n");
      out.write("			contentType: \"application/json;charset=utf-8\",\r\n");
      out.write("			data : JSON.stringify(postString),\r\n");
      out.write("			success : function(resp){\r\n");
      out.write("				alert(resp);\r\n");
      out.write("				loadData(\"\",\"\");\r\n");
      out.write("			},\r\n");
      out.write("			beforeSend : showRequest,\r\n");
      out.write("			error : function(e){\r\n");
      out.write("				alert(\"실패 : \" + e)\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		}) //ajax\r\n");
      out.write("	}) //send\r\n");
      out.write("	\r\n");
      out.write("})// document\r\n");
      out.write("//상세보기\r\n");
      out.write(" function fview(num){\r\n");
      out.write("	$.getJSON(\"view\", \r\n");
      out.write("			           {num : num}, \r\n");
      out.write("			           function(resp){\r\n");
      out.write("			        	   var  str =\"\"\r\n");
      out.write("			        	   str += \"번호  : \" + resp.num +\"<br/>\"\r\n");
      out.write("			        	   str += \"이름  : \" + resp.name +\"<br/>\"\r\n");
      out.write("			        	   str += \"내용  : \" + resp.content +\"<br/>\"\r\n");
      out.write("			        	   str += \"평가  : \" + resp.grade +\"<br/>\"\r\n");
      out.write("			        	   str += \"작성일  : \" + resp.created +\"<br/>\"\r\n");
      out.write("			        	$(\"#viewDiv\").html(str)\r\n");
      out.write("		\r\n");
      out.write("	}) // getJSON\r\n");
      out.write("}//fview \r\n");
      out.write("\r\n");
      out.write("//삭제\r\n");
      out.write("function fdelete(num){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type: \"DELETE\",\r\n");
      out.write("		url : \"delete/\"+num,    //delete?num=6 (get방식)\r\n");
      out.write("		success : function(resp){\r\n");
      out.write("			alert(resp + \"삭제 성공\")\r\n");
      out.write("			loadData(\"\",\"\")\r\n");
      out.write("		},\r\n");
      out.write("		error:function(e){\r\n");
      out.write("			alert(\"삭제실패 : \" + e)\r\n");
      out.write("		}\r\n");
      out.write("	})//ajax\r\n");
      out.write("}  //fdelete\r\n");
      out.write("\r\n");
      out.write("/* function fdelete(num){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		type: \"post\",\r\n");
      out.write("		url : \"delete\",\r\n");
      out.write("		data : {num : num},\r\n");
      out.write("		success : function(resp){\r\n");
      out.write("			alert(resp + \"삭제 성공\")\r\n");
      out.write("			loadData(\"\",\"\")\r\n");
      out.write("		},\r\n");
      out.write("		error:function(e){\r\n");
      out.write("			alert(\"삭제실패 : \" + e)\r\n");
      out.write("		}\r\n");
      out.write("	})//ajax\r\n");
      out.write("}  //fdelete */\r\n");
      out.write("function loadData(field, word){\r\n");
      out.write("	  $.getJSON(\r\n");
      out.write("			 \"list\",\r\n");
      out.write("			  {\"field\" : field, \"word\" : word},\r\n");
      out.write("			  function(resp){\r\n");
      out.write("				  var str =\"\"\r\n");
      out.write("				  $.each(resp.arr, function(key,val){\r\n");
      out.write("					 str +=val.num +\"  \"\r\n");
      out.write("					 str +=\"<a href='javascript:fview(\"+val.num+\")'>\"+val.name +\"</a>   \"\r\n");
      out.write("					 str +=val.content +\"  \"\r\n");
      out.write("					 str += val.grade +\"  \"\r\n");
      out.write("					 str +=\"<a href='javascript:fdelete(\"+val.num+\")'>삭제</a><br/>\"\r\n");
      out.write("				  })//each\r\n");
      out.write("				  $(\"#cnt\").text(\"개수 : \" + resp.count)\r\n");
      out.write("				 $(\"#result\").html(str);\r\n");
      out.write("			  }\r\n");
      out.write("	  ) //getJSON\r\n");
      out.write("}  //loadData\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showRequest(){\r\n");
      out.write("	if($(\"#name\").val()==\"\"){\r\n");
      out.write("		alert(\"글쓴이를 입력하세요\")\r\n");
      out.write("		$(\"#name\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if(!$(\"#content\").val()){\r\n");
      out.write("		alert(\"내용을 입력하세요\")\r\n");
      out.write("		$(\"#content\").focus();\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	if($(\"input:radio[name=grade]:checked\").length==0){\r\n");
      out.write("		alert(\"평가하세요\")\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	return true;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"insert\" method=\"post\" >\r\n");
      out.write("<table>\r\n");
      out.write("	<tr>\r\n");
      out.write("				<td >글쓴이</td>\r\n");
      out.write("				<td><input type=\"text\" id=\"name\" name=\"name\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >내 용</td>\r\n");
      out.write("				<td><input type=\"text\" size=\"80\" id=\"content\" name=\"content\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td >평가</td>\r\n");
      out.write("				<td>\r\n");
      out.write("				<input  type=\"radio\" name=\"grade\" value=\"excellent\" checked>아주잘함(excellent)\r\n");
      out.write("				<input  type=\"radio\" name=\"grade\" value=\"good\"> 잘함(good) \r\n");
      out.write("				<input 	type=\"radio\" name=\"grade\" value=\"normal\"> 보통(normal) \r\n");
      out.write("				<input 	type=\"radio\" name=\"grade\" value=\"fail\"> 노력(fail)</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td colspan=\"2\">\r\n");
      out.write("				 <input type=\"button\" value=\"입력\" id=\"send\">\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div id=\"cnt\"></div>\r\n");
      out.write("<div id=\"result\"></div>\r\n");
      out.write("<hr/>\r\n");
      out.write("<div id=\"viewDiv\"></div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
